version: '3'
services:
  pool:
    privileged: true
    security_opt:
      - seccomp:unconfined
    build: .
    volumes:
      - .:/home/pythia
    links:
      - queue
    entrypoint: ./out/pythia -queue "queue:9000" pool & mount -av
  queue:
    privileged: true
    security_opt:
      - seccomp:unconfined
    build: .
    ports:
      - "9000:9000"
    volumes:
      - .:/home/pythia
    entrypoint: ./out/pythia -queue "0.0.0.0:9000" queue 
  server:
    privileged: true
    security_opt:
      - seccomp:unconfined
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/home/pythia
    links:
      - queue
    entrypoint: ./out/pythia -queue "queue:9000" server
